services:
  dev:
    build: .
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "artisan", "serve", "--host=0.0.0.0"]
    ports:
      - 8000:8000
    depends_on:
      - database

  artisan:
    build: .
    volumes:
      - ./src:/var/www/html
    entrypoint: ["php", "artisan"]