services:
  server:
      image: 'nginx:stable-alpine'
      ports:
        - "8080:80"
      volumes:
        - ./src:/var/www/html
        - ./docker-conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - php
        - database
  php:
    build: .
    volumes:
      - ./src:/var/www/html:delegated
    ports:
      - "9000:9000"

  database:
    image: postgres:15
    env_file:
      - "./docker-conf/postgres.env"
      - postgres-data:/var/lib/posgresql/data
    ports:
      - "5432:5432"

volumes:
  posgresql-data: